def countNucleotides(text: str) -> dict[str, int]:
    """consider adding docstring"""
    # Count each nucleotide inside the function
    count_a = text.count("A")
    count_c = text.count("C")
    count_g = text.count("G")
    count_t = text.count("T")
    
    # Return the results as a dictionary matching the type hint
    return {
        "A": count_a,
        "C": count_c,
        "G": count_g,
        "T": count_t
    }

# Your DNA sequence string
s = "CCCGCCCGAAGATGCAAGGAGACGCAATGGGGTATCTAGCCATTATCTTACTTATGACTTTGTGGCCAAAATAGGTGGGCATGGACTCCCGCAATCAACCCAGTCAAGCGAATATAAGTTATTCCTGCATTCTGAACGAGCGGTGCAGTACATAGTGTACCCATTACTGTGGTCCGAATCCTGGGTAGCGGATGGTGCTTGAATATTTATTCCTCCGGGCCATCAAGCGTGGCGTCAGGTTGCCACCGCGGTGTAGCCGACCGTCAGCTTATGCGAAATTAAAGTTGGACGAGCGACAAGGTTCTACAGAATTGTGGGGGCCTTAAAGTTTTAATGGGGGACGGCGTGGGCATAAACAAGGGAATATGGGGGTTTGGGTTGACCCACTCGGGCGCTCGCCATCCAATGAGCGCTCTCATCCGACCCAGTTCGATCAAGGCAACGGCGTTGTTAGGTTATTACTAAAGATAATCCGTGGATTCTTTCTATGAACAGCGTTCATTAATGAAATACTGTGGTAGTATGTTAAATTACTGGGATGGAGACCTCTTCGGTAGTGCTGTGTTGTAGCACAGATTATCCAATACTACGTGCAGTGTAAACGTGTCCCTCGAAGTGCTTCCGAGCGAGGCATAATACCAGCAACAGATATAGCGTTCTTGTTCTATAGGCCGCTCACAGACATCTTGACCGTGTACTTGGATATTATTATGTCCATATAAATTGATTGATCGAGAACTGAAAAGCCTCTGCTAAACTAGGGGCGTACATTTACCGCAACTCCGGCACGCCGTGGGGTCTCACCGGTAAATGTGCACGCTTTCATTGTCGGGCGTGCCCATGTCAGTAGATACTTACAGGATGTACGCAGGTGTTTCTCGATATTTATCTCAA"

# Call the function and get the counts
counts = countNucleotides(s)

# Print the format you wanted: "A_count C_count G_count T_count"
print(f"{counts['A']} {counts['C']} {counts['G']} {counts['T']}")
