#from itertools import count

def patternCount(text: str, pattern: str) -> int:
    """Count occurrences of a pattern in text.
    
    Matches are case-sensitive and may overlap. Assume pattern is nonempty.
    Return 0 if pattern is longer than text or text is empty.

    Example:
        PatternCount("AAAA", "AA") returns 3.
    """
    count = 0
    k = len(pattern)
    
    # Return 0 if text is empty or pattern is longer than text
    if not text or k > len(text):
        return 0
        
    for i in range(len(text) - k + 1):
        if text[i : i + k] == pattern:
            count += 1
    return count

# Test Data
text = "CAATAATGGAGTCCTTAGTCCTTTAGTCCTTGGACGAGTCCTTAGTCCTTCAGTCCTTACGAGTCCTTAAGTCCTTCAGTCCTTATAGTCCTTAGTCCTTAGCTAGTCCTTGCACTCGCTTTGTGTCCACAAGTCCTTTGAAAAAGTCCTTAGGAAAGTCCTTAGTCCTTTAGTCCTTTGACCTAGTCCTTAAGTCCTTTGACTATGAGTCCTTAGTCCTTAGTCCTTCAAGTCCTTAGTCCTTCAGTCCTTCAGAGTCCTTAGTCCTTAGTCCTTAGTCCTTTCCAGTCCTTAGTCCTTGTTAGTCCTTCCTCCCAGTCCTTGGAGTCCTTAGTCCTTAAAGTCCTTAAGTCCTTAGTCCTTCAGTCCTTGAGTCCTTCGACGACCACCAAGTCCTTGAGTCCTTAGAGCCCGAAGTCCTTAGTCCTTCTAGTCCTTCTTCAGTCCTTATCTGTATCAGTGTTATGCCCCAGATAGTCCTTAGTCCTTTTTAAGTCCTTAAGTCCTTAAAGTCCTTGAAGTCCTTAGTCCTTTTCTAGGAGTCCTTAAGGAGGTCGCAGTCCTTCAGTCCTTAATCTTGTAACAGTCCTTAGTCCTTTATGGAGTCCTTCTAGGAGTCCTTGCTAGTCCTTGAAAAGTCCTTTCAGTCCTTAGTCCTTGGTCAAGTCCTTTTACAGTCCTTAGTCCTTCGGCGATCAGTCCTTTCAGTCCTTAGTCCTTCGCATCTAGTCCTTCAGAGTCCTTGTCAGTCCTTGAAGTCCTTAGTCCTTAGTCCTTGAGTCCTTCCGGCAGTCCTTAGTCCTTTAGTCCTTAGTCCTTTAGTCCTTTGAGTCCTTCAGTCCTTAGTCCTTATGTAAGTCCTTTTGCCAGTCCTTCAGGCTGTAGGCACTAGTCCTTTTGAGTCCTTGGAACAGTCCTTGCTAGTCCTTAGTCCTTCAAGTCCTTTAGTCCTTAAAGCCCAGTCCTTTAGTCCTTCAGTCCTTCAAGTCCTTAGAGTCCTT"
pattern = "AGTCCTTAG"

# Print Output
print(patternCount(text, pattern))