"""Count occurrences of a pattern in text."""


from itertools import count
from xml.dom.minidom import Text


def PatternCount(text: str, pattern: str) -> int:
    """Return the number of occurrences of pattern in text.


    Matches are case-sensitive and may overlap. Assume pattern is nonempty.
    Return 0 if pattern is longer than text or text is empty.

    Example:
        PatternCount("AAAA", "AA") returns 3.
    """

    # TODO: Implement this function.
    raise NotImplementedError("Implement PatternCount")

def pattern_count(text, pattern):
    count = 0
    k = len(pattern)
    for i in range(len(text) - k + 1):
        if text[i : i + k] == pattern:
            count += 1
    return count
text = "CAATAATGGAGTCCTTAGTCCTTTAGTCCTTGGACGAGTCCTTAGTCCTTCAGTCCTTACGAGTCCTTAAGTCCTTCAGTCCTTATAGTCCTTAGTCCTTAGCTAGTCCTTGCACTCGCTTTGTGTCCACAAGTCCTTTGAAAAAGTCCTTAGGAAAGTCCTTAGTCCTTTAGTCCTTTGACCTAGTCCTTAAGTCCTTTGACTATGAGTCCTTAGTCCTTAGTCCTTCAAGTCCTTAGTCCTTCAGTCCTTCAGAGTCCTTAGTCCTTAGTCCTTAGTCCTTTCCAGTCCTTAGTCCTTGTTAGTCCTTCCTCCCAGTCCTTGGAGTCCTTAGTCCTTAAAGTCCTTAAGTCCTTAGTCCTTCAGTCCTTGAGTCCTTCGACGACCACCAAGTCCTTGAGTCCTTAGAGCCCGAAGTCCTTAGTCCTTCTAGTCCTTCTTCAGTCCTTATCTGTATCAGTGTTATGCCCCAGATAGTCCTTAGTCCTTTTTAAGTCCTTAAGTCCTTAAAGTCCTTGAAGTCCTTAGTCCTTTTCTAGGAGTCCTTAAGGAGGTCGCAGTCCTTCAGTCCTTAATCTTGTAACAGTCCTTAGTCCTTTATGGAGTCCTTCTAGGAGTCCTTGCTAGTCCTTGAAAAGTCCTTTCAGTCCTTAGTCCTTGGTCAAGTCCTTTTACAGTCCTTAGTCCTTCGGCGATCAGTCCTTTCAGTCCTTAGTCCTTCGCATCTAGTCCTTCAGAGTCCTTGTCAGTCCTTGAAGTCCTTAGTCCTTAGTCCTTGAGTCCTTCCGGCAGTCCTTAGTCCTTTAGTCCTTAGTCCTTTAGTCCTTTGAGTCCTTCAGTCCTTAGTCCTTATGTAAGTCCTTTTGCCAGTCCTTCAGGCTGTAGGCACTAGTCCTTTTGAGTCCTTGGAACAGTCCTTGCTAGTCCTTAGTCCTTCAAGTCCTTTAGTCCTTAAAGCCCAGTCCTTTAGTCCTTCAGTCCTTCAAGTCCTTAGAGTCCTT"
pattern = "AGTCCTTAG"

print(pattern_count(text, pattern)) 

